export default {
    en: {
        curated: "Co-curated by Femzor & Occulted",
        p1: "The internet emerges as an archipelago of digital islands, geologies of code reshaped by tides of interaction and innovation to form subterranean spaces of virtuality that flicker across the expanse of cyberspace.", 
        p2: "Here we set the stage to bring together a new generation of artists who were drawn to these transitory sites as a space in which to probe prototypes of their selves as beta versions of an artistic consciousness unbound by the limitations of flesh and geography. Embracing a relationship with technology that subverts simple acts of consumption in favour of new forms of expression that transmute traditional artistic precepts through the reactive terrain of pixels and software towards a lived experience of the contemporary internet.",
        p3: "We see the production of art in this context as coming to to represent a certain re-beginning of creative expression. Where, cast out across the imagination an immediate, globally connected network, the chaotic synaptic firings of the modern internet are rewired into assemblages of affectivity. Passing beyond simple acts of digitisation to form vestiges of meaning amidst an endless tide of informatics. Leveraging transversal forms of digital technology in fight against the potential sublimation of our imaginations and towards acts of creation as a reimagining of the possible.",
        p4: "In the world of Hyperescapismo, we invite you to join us along with 19 other artists in a search for such a reimagining. Creating a new 1/1 work to be exhibited and auctioned within the universe we have created with Femzor and Occulted. We wish the works across the islands to stand as manifestations to each artists own experience and vision as well as push forward a new era of possibilities for curating, displaying and collecting groundbreaking digital art.",
        join: "Join us"
    },
    pt: {
        curated: "Co-curadoria por Femzor & Occulted",
        p1: "A internet emerge como um arquipélago de ilhas digitais, geologias de código remodeladas por marés de interação e inovação para formar espaços subterrâneos de virtualidade que cintilam através da expansão do ciberespaço.", 
        p2: "Aqui, preparamos o cenário para reunir uma nova geração de artistas que foram atraídos a estes locais transitórios como um espaço para sondar protótipos de seus eus como versões beta de uma consciência artística livre das limitações da carne e da geografia. Abraçando uma relação com a tecnologia que subverte simples atos de consumo em favor de novas formas de expressão que transmutam preceitos artísticos tradicionais através do terreno reativo de pixels e software rumo a uma experiência vivida da internet contemporânea.",
        p3: "Vemos a produção de arte neste contexto como representando um certo recomeço da expressão criativa. Onde, lançados através da imaginação de uma rede imediata e globalmente conectada, os caóticos disparos sinápticos da internet moderna são reconectados em conjuntos de afetividade. Ultrapassando simples atos de digitalização para formar vestígios de significado em meio a uma maré interminável de informática.",
        p4: "Aproveitando formas transversais de tecnologia digital na luta contra a potencial sublimação de nossas imaginações e em direção a atos de criação como uma reimaginação do possível. No mundo do Hyperescapismo, convidamos você a se juntar a nós e a outros 19 artistas em uma busca por tal reimaginação. Criando uma nova obra 1/1 para ser exibida e leiloada dentro do universo que criamos com Femzor e Occulted. Desejamos que as obras nas ilhas se destaquem como manifestações da própria experiência e visão de cada artista, além de impulsionar uma nova era de possibilidades para curadoria, exibição e coleção de arte digital inovadora.",
        join: "Junte-se a nós"
    },
    es: {
        curated: "Co-curado por Femzor & Occulted",
        p1: "Internet emerge como un archipiélago de islas digitales, geologías de código remodeladas por mareas de interacción e innovación para formar espacios subterráneos de virtualidad que titilan a lo largo de la extensión del ciberespacio.", 
        p2: "Acá armamos el escenario para juntar a una nueva generación de artistas que se sintieron atraídos por estos sitios transitorios como un espacio en el cual sondear prototipos de sus propios yo como versiones beta de una conciencia artística liberada de las limitaciones de la carne y la geografía. Abraza una relación con la tecnología que subvierte simples actos de consumo a favor de nuevas formas de expresión, transmutando preceptos artísticos tradicionales a en un terreno reactivo de píxeles y software hacia una experiencia vivida de la internet contemporánea.",
        p3: "Vemos la producción de arte en este contexto como una representación de cierto reinicio de la expresión creativa. Donde, proyectados a través de la imaginación de una red inmediata y globalmente conectada, los caóticos disparos sinápticos de la internet moderna se reconectan en ensamblajes de afectividad. Pasando más allá de simples actos de digitalización para formar vestigios de significado en medio de una marea interminable de informática. Aprovechando formas transversales de tecnología digital en la lucha contra la potencial sublimación de nuestras imaginaciones y hacia actos de creación como una reimaginación de lo posible.",
        p4: "En el mundo del Hyperescapismo, te invitamos a que te sumes a nosotros junto con otros 19 artistas en una búsqueda de tal reimaginación. Creando una nueva obra 1/1 para ser exhibida y subastada dentro del universo que hemos creado con Femzor y Occulted. Queremos que las obras a lo largo de las islas se erijan como manifestaciones de la propia experiencia y visión de cada artista, así como que impulsen una nueva era de posibilidades para curar, exhibir y coleccionar arte digital innovador.",
        join: "Unirse"
    },
  };